### ISSUE TITLE
Panic when connection IP address changes

### ISSUE THREAD

**Issue by WesleyRosenblum** [mozilla/neqo#1289]
When testing neqo server, we are seeing a panic when the client changes the IP address it uses for a connection:

```
sim             | 1s:  rebinding: 193.167.0.100:58999 -> 193.167.0.252:52072
..
server          | 1s235ms INFO [Server 74d85742e9007e5d] Rx ACK space=ap, ranges=[2..=18]
server          | 1s235ms INFO [unv-path:c99a0575ac73f4019ad98072b61c84bc [::]:443->[::ffff:193.167.0.252]:52072] set as primary path
..
server          | 1s269ms INFO [Server 74d85742e9007e5d] Rx ACK space=ap, ranges=[38..=38]
server          | thread 'main' panicked at 'assertion failed: self.bytes_in_flight >= pkt.size', neqo-transport/src/cc/classic_cc.rs:250:13
server          | stack backtrace:
server          |    0: backtrace::backtrace::libunwind::trace
server          |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
server          |    1: backtrace::backtrace::trace_unsynchronized
server          |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
server          |    2: std::sys_common::backtrace::_print_fmt
server          |              at src/libstd/sys_common/backtrace.rs:78
server          |    3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
server          |              at src/libstd/sys_common/backtrace.rs:59
server          |    4: core::fmt::write
server          |              at src/libcore/fmt/mod.rs:1076
server          |    5: std::io::Write::write_fmt
server          |              at src/libstd/io/mod.rs:1537
server          |    6: std::sys_common::backtrace::_print
server          |              at src/libstd/sys_common/backtrace.rs:62
server          |    7: std::sys_common::backtrace::print
server          |              at src/libstd/sys_common/backtrace.rs:49
server          |    8: std::panicking::default_hook::{{closure}}
server          |              at src/libstd/panicking.rs:198
server          |    9: std::panicking::default_hook
server          |              at src/libstd/panicking.rs:218
server          |   10: std::panicking::rust_panic_with_hook
server          |              at src/libstd/panicking.rs:486
server          |   11: std::panicking::begin_panic
server          |              at ./rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libstd/panicking.rs:410
server          |   12: <neqo_transport::cc::classic_cc::ClassicCongestionControl<T> as neqo_transport::cc::CongestionControl>::on_packets_lost
server          |              at neqo-transport/src/cc/classic_cc.rs:250
```

Thanks for considering this issue and let me know if you need any further information!

**Comment by Grubba27** [comment]
Is this a good beginners issue ? 
i would change this assertion for something else ?

 ```rust
        for pkt in lost_packets.iter().filter(|pkt| pkt.cc_in_flight()) {
            assert!(self.bytes_in_flight >= pkt.size);
            self.bytes_in_flight -= pkt.size;
        }
```

and how I could add tests to this refactor ?

**Comment by martinthomson** [comment]
Unfortunately, this one is going to be fairly complex to track down.  We already have tests for the case in question, so fixing this would first require understanding the exact conditions that produced the error in some detail.  I'd suggest starting somewhere else.

**Comment by larseggert** [comment]
@WesleyRosenblum do you have a way for us to reproduce this?

**Comment by WesleyRosenblum** [comment]
We've enabled the QUIC interop runner `rebind-addr` test in our local version of QNS, which is included in the `s2n-quic` source code. That test is how we noticed this panic.

If you clone the [s2n-quic repo](https://github.com/aws/s2n-quic), you should be able to run the following command to reproduce this:
`./scripts/interop/run --client s2n-quic --server neqo --test rebind-addr`

Here's the panic in a run I just executed:

```
server  | thread 'main' panicked at neqo-transport/src/cc/classic_cc.rs:182:13:
server  | assertion failed: self.bytes_in_flight >= pkt.size
server  | stack backtrace:
server  |    0: rust_begin_unwind
server  |              at ./rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
server  |    1: core::panicking::panic_fmt
server  |              at ./rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
server  |    2: core::panicking::panic
server  |              at ./rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:144:5
server  |    3: <neqo_transport::cc::classic_cc::ClassicCongestionControl<T> as neqo_transport::cc::CongestionControl>::on_packets_acked
server  |              at ./neqo/neqo-transport/src/cc/classic_cc.rs:182:13
server  |    4: neqo_transport::sender::PacketSender::on_packets_acked
server  |              at ./neqo/neqo-transport/src/sender.rs:81:9
server  |    5: neqo_transport::path::Path::on_packets_acked
server  |              at ./neqo/neqo-transport/src/path.rs:964:9
server  |    6: neqo_transport::recovery::LossRecovery::on_ack_received
server  |              at ./neqo/neqo-transport/src/recovery.rs:745:9
server  |    7: neqo_transport::connection::Connection::handle_ack
server  |              at ./neqo/neqo-transport/src/connection/mod.rs:2890:45
server  |    8: neqo_transport::connection::Connection::input_frame
server  |              at ./neqo/neqo-transport/src/connection/mod.rs:2705:17
server  |    9: neqo_transport::connection::Connection::process_packet
server  |              at ./neqo/neqo-transport/src/connection/mod.rs:1570:29
server  |   10: neqo_transport::connection::Connection::input_path
server  |              at ./neqo/neqo-transport/src/connection/mod.rs:1501:31
server  |   11: neqo_transport::connection::Connection::input
server  |              at ./neqo/neqo-transport/src/connection/mod.rs:1449:19
server  |   12: neqo_transport::connection::Connection::process
server  |              at ./neqo/neqo-transport/src/connection/mod.rs:1103:13
server  |   13: neqo_transport::server::Server::process_connection
server  |              at ./neqo/neqo-transport/src/server.rs:277:19
server  |   14: neqo_transport::server::Server::process_input
server  |              at ./neqo/neqo-transport/src/server.rs:570:20
server  |   15: neqo_transport::server::Server::process::{{closure}}
server  |              at ./neqo/neqo-transport/src/server.rs:670:27
server  |   16: core::option::Option<T>::and_then
server  |              at ./rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/option.rs:1406:24
server  |   17: neqo_transport::server::Server::process
server  |              at ./neqo/neqo-transport/src/server.rs:670:14
server  |   18: neqo_bin::server::ServersRunner::process::{{closure}}
server  |              at ./neqo/neqo-bin/src/server/mod.rs:522:19
server  |   19: neqo_bin::server::ServersRunner::run::{{closure}}
server  |              at ./neqo/neqo-bin/src/server/mod.rs:570:52
server  |   20: neqo_bin::server::server::{{closure}}
server  |              at ./neqo/neqo-bin/src/server/mod.rs:640:26
server  |   21: neqo_server::main::{{closure}}
server  |              at ./neqo/neqo-bin/src/bin/server.rs:13:36
server  |   22: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
server  |              at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/park.rs:281:63
server  |   23: tokio::runtime::coop::with_budget
server  |              at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/coop.rs:107:5
server  |   24: tokio::runtime::coop::budget
server  |              at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/coop.rs:73:5
server  |   25: tokio::runtime::park::CachedParkThread::block_on
server  |              at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/park.rs:281:31
server  |   26: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
server  |              at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context/blocking.rs:66:9
server  |   27: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}
server  |              at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
server  |   28: tokio::runtime::context::runtime::enter_runtime
server  |              at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context/runtime.rs:65:16
server  |   29: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
server  |              at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
server  |   30: tokio::runtime::runtime::Runtime::block_on
server  |              at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/runtime.rs:351:50
server  |   31: neqo_server::main
server  |              at ./neqo/neqo-bin/src/bin/server.rs:13:5
server  |   32: core::ops::function::FnOnce::call_once
server  |              at ./rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
server  | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
server exited with code 101
```

**Comment by larseggert** [comment]
Thanks! That was very simple, but on my (macOS) box, the client doesn't seem to start:
```
client  | Setting up routes...
client  | Actual changes:
client  | tx-checksum-ip-generic: off
client  | tx-tcp-segmentation: off [not requested]
client  | tx-tcp-ecn-segmentation: off [not requested]
client  | tx-tcp-mangleid-segmentation: off [not requested]
client  | tx-tcp6-segmentation: off [not requested]
client  | tx-checksum-sctp: off
client  | Endpoint's IPv4 address is 193.167.0.100
client  | Endpoint's IPv6 address is fd00:cafe:cafe::100
client  | aarch64
client  | Error: TC classifier not found.
client  | We have an error talking to the kernel
```
I guess I should try on Linux.

**Comment by larseggert** [comment]
OK, got it running on Linux and can reproduce.

(And have you considered doing a PR for @marten-seemann's main quic-interop-runner based on https://github.com/quic-interop/quic-network-simulator/compare/master...WesleyRosenblum:quic-network-simulator:master? It would be great to have those improvements/additions in the main repo!)

**Comment by WesleyRosenblum** [comment]
Thanks for fixing this @larseggert!

> (And have you considered doing a PR for @marten-seemann's main quic-interop-runner based on https://github.com/quic-interop/quic-network-simulator/compare/master...WesleyRosenblum:quic-network-simulator:master? It would be great to have those improvements/additions in the main repo!)

I have to take a look at these changes (its been a while), but it would be great to get them upstreamed.
