### ISSUE TITLE
error: could not compile `neqo-common` due to 4 previous errors

### ISSUE THREAD

**Issue by feters** [mozilla/neqo#1332]
I am following the linux build and dockerfile for building but keep stuck at this error when doing cargo build.

error: could not compile `neqo-common` due to 4 previous errors

```
error[E0061]: this function takes 4 arguments but 3 arguments were supplied
    --> neqo-common/src/log.rs:16:13
     |
16   |             ::log::__private_api_log(
     |             ^^^^^^^^^^^^^^^^^^^^^^^^ expected 4 arguments
17   |                 ::log::__log_format_args!($($arg)+),
18   |                 lvl,
     |                 ---
19   |                 &($target, ::log::__log_module_path!(), ::log::__log_file!(), ::log::__log_line!()),
     |                 ----------------------------------------------------------------------------------- supplied 3 arguments
...
60   |             do_log!(::log::Level::Info, "Logging initialization error {:?}", e);
     |             -------------------------------------------------------------------
     |             |
     |             in this macro invocation
     |
note: function defined here
    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/log-0.4.16/src/lib.rs:1576:8
     |
1576 | pub fn __private_api_log(
     |        ^^^^^^^^^^^^^^^^^
     = note: this error originates in the macro `$crate::do_log` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0061`.
error: could not compile `neqo-common` due to 4 previous errors

Caused by:
  process didn't exit successfully: `rustc --crate-name neqo_common --edition=2018 neqo-common/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="deny-warnings"' -C metadata=cbd48452ed35b24a -C extra-filename=-cbd48452ed35b24a --out-dir /src/neqo/target/debug/deps -C incremental=/src/neqo/target/debug/incremental -L dependency=/src/neqo/target/debug/deps --extern chrono=/src/neqo/target/debug/deps/libchrono-4896f07c16cee554.rmeta --extern env_logger=/src/neqo/target/debug/deps/libenv_logger-c1ca2f2bb9193a60.rmeta --extern lazy_static=/src/neqo/target/debug/deps/liblazy_static-02ff0d0fbc57b9b4.rmeta --extern log=/src/neqo/target/debug/deps/liblog-38ede5edb5cb0d57.rmeta --extern qlog=/src/neqo/target/debug/deps/libqlog-99ded8192d30c386.rmeta` (exit status: 1)
warning: build failed, waiting for other jobs to finish...
error: build failed
```

do I miss something?
please help and thank you.

**Comment by martinthomson** [comment]
I just discovered the same problem too.  @valenting added a dependency on a public-but-not-really API in the `log` crate.  I've a patch that addresses the problem coming.

**Comment by feters** [comment]
@martinthomson thank you very much for resolving the issue, everything works fine now but an error like this still appears #1166 

```
H3 Client connecting: 0.0.0.0:34770 -> 127.0.0.1:7733
Cannot create stream Err(Unavailable)
Cannot create stream Err(Unavailable)
Successfully created stream id 0 for http://127.0.0.1:7733/10m.txt
Saving http://127.0.0.1:7733/10m.txt to "client_download/10m.txt"
```

**Comment by martinthomson** [comment]
If you mean the "Cannot create stream Err(Unavailable)", that's normal operation.  We should probably suppress that logging, as it is perfectly normal.

**Comment by feters** [comment]
@martinthomson oh I see thank you, however, I'm trying with lsquic server and got this similar error.
I check at QUIC Interop Runner, lsquic_server - neqo_client should work.

```
H3 Client connecting: 0.0.0.0:36332 -> 172.17.0.3:4433
thread 'main' panicked at 'Can't create stream HTTP/3 error: AlreadyClosed', neqo-client/src/main.rs:501:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

with bactrace=1
```
H3 Client connecting: 0.0.0.0:46978 -> 172.17.0.3:4433
0s  0ms INFO Logging initialized
0s  0ms INFO [CryptoStates] Creating initial cipher state v=Version2, role=Client dcid=84ba35f9a68da93d
0s  0ms TRACE new_initial Version2 84ba35f9a68da93d
0s  0ms INFO Making Write 0 CryptoDxState, v=Version2 cipher=4865
0s  0ms TRACE new_initial Version2 84ba35f9a68da93d
0s  0ms INFO Making Read 0 CryptoDxState, v=Version2 cipher=4865
0s  0ms INFO [CryptoStates] Creating initial cipher state v=Version1, role=Client dcid=84ba35f9a68da93d
0s  0ms TRACE new_initial Version1 84ba35f9a68da93d
0s  0ms INFO Making Write 0 CryptoDxState, v=Version1 cipher=4865
0s  0ms TRACE new_initial Version1 84ba35f9a68da93d
0s  0ms INFO Making Read 0 CryptoDxState, v=Version1 cipher=4865
0s  0ms DEBUG [unv-path 0.0.0.0:46978->172.17.0.3:4433] Make permanent
0s  0ms INFO [unv-path:84ba35f9a68da93d 0.0.0.0:46978->172.17.0.3:4433] set as primary path
0s  0ms TRACE [unv-path:84ba35f9a68da93d 0.0.0.0:46978->172.17.0.3:4433] Make primary true
0s  0ms DEBUG [pri-unv-path:84ba35f9a68da93d 0.0.0.0:46978->172.17.0.3:4433] Path validated Instant { tv_sec: 877638, tv_nsec: 507033491 }
0s  1ms DEBUG Decoder: creating a new qpack decoder.
0s  1ms TRACE [Http3 client] Process output.
0s  1ms TRACE [Http3 client] Process http3 internal.
0s  1ms TRACE [Http3 client] Check connection events.
0s  1ms TRACE [Client 84ba35f9a68da93d] process_output Init Instant { tv_sec: 877638, tv_nsec: 508500465 }
0s  1ms INFO [Client 84ba35f9a68da93d] client_start
0s  1ms TRACE [Client 84ba35f9a68da93d] Handshake space=in data=None
0s  2ms DEBUG Writing transport parameters, msg=1
0s  2ms DEBUG TP encoded; type 0x09 val Integer(16)
0s  2ms DEBUG TP encoded; type 0x0c val Empty
0s  2ms DEBUG TP encoded; type 0x07 val Integer(1048576)
0s  2ms DEBUG TP encoded; type 0x08 val Integer(16)
0s  2ms DEBUG TP encoded; type 0x0e val Integer(8)
0s  2ms DEBUG TP encoded; type 0x0b val Integer(20)
0s  2ms DEBUG TP encoded; type 0x01 val Integer(30000)
0s  2ms DEBUG TP encoded; type 0x2ab2 val Empty
0s  2ms DEBUG TP encoded; type 0x05 val Integer(1048576)
0s  2ms DEBUG TP encoded; type 0xff73db val Versions { current: 1, other: [451582634, 1889161412, 1] }
0s  2ms DEBUG TP encoded; type 0xff02de1a val Integer(1000)
0s  2ms DEBUG TP encoded; type 0x06 val Integer(1048576)
0s  3ms DEBUG TP encoded; type 0x04 val Integer(4611686018427387903)
0s  3ms DEBUG TP encoded; type 0x20 val Integer(0)
0s  3ms DEBUG TP encoded; type 0x0f val Bytes([])
0s  3ms INFO [Agent 0x55f8485c3340] state -> InProgress
0s  3ms TRACE [Crypto] Adding CRYPTO data Record 0:22 [512]: 010001fc03031180685697b85c5449ca9263f70934e3fbacbeea60eb19bac70d3e710da5d38d000006130113031302010001cd00170000ff01000100000a00140012001d00170018001901000101010201030104001000050003026833000500050100000000003300260024001d0020dfbef8b492487e4c043282182ded22808a4b87839be03515a89370105f5a402c002b0003020304000d0018001604030503060302030804080508060401050106010201002d00020101001c00024001003900580901100c000704801000000801100e01080b01140104800075306ab20005048010000080ff73db10000000011aea9aaa709a50c400000001c0000000ff02de1a0243e80604801000000408ffffffffffffffff2001000f00001500e1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0s  3ms INFO [Client 84ba35f9a68da93d] State change from Init -> WaitInitial
0s  3ms TRACE [0x55f8485c3340] got ALPN None
0s  3ms TRACE [Client 84ba35f9a68da93d] output Instant { tv_sec: 877638, tv_nsec: 508500465 }
0s  3ms DEBUG [LossRecovery] get send profile Instant { tv_sec: 877638, tv_nsec: 508500465 }
0s  3ms DEBUG [Client 84ba35f9a68da93d] output_path send_profile SendProfile { limit: 1357, pto: None, probe: (), paced: false }
0s  3ms DEBUG Building Initial dcid 84ba35f9a68da93d scid
0s  3ms DEBUG CRYPTO for in offset=0, len=512
0s  3ms DEBUG [Client 84ba35f9a68da93d] pn=0 type=Initial pri-path:84ba35f9a68da93d 0.0.0.0:46978->172.17.0.3:4433
  TX -> Crypto { offset: 0, len: 512 }
0s  4ms TRACE Packet build pn=0 hdr=c0000000010884ba35f9a68da93d0000421500 body=06004200010001fc03031180685697b85c5449ca9263f70934e3fbacbeea60eb19bac70d3e710da5d38d000006130113031302010001cd00170000ff01000100000a00140012001d00170018001901000101010201030104001000050003026833000500050100000000003300260024001d0020dfbef8b492487e4c043282182ded22808a4b87839be03515a89370105f5a402c002b0003020304000d0018001604030503060302030804080508060401050106010201002d00020101001c00024001003900580901100c000704801000000801100e01080b01140104800075306ab20005048010000080ff73db10000000011aea9aaa709a50c400000001c0000000ff02de1a0243e80604801000000408ffffffffffffffff2001000f00001500e1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0s  4ms TRACE [epoch 0 Write] encrypt pn=0 hdr=c0000000010884ba35f9a68da93d0000421500 body=06004200010001fc03031180685697b85c5449ca9263f70934e3fbacbeea60eb19bac70d3e710da5d38d000006130113031302010001cd00170000ff01000100000a00140012001d00170018001901000101010201030104001000050003026833000500050100000000003300260024001d0020dfbef8b492487e4c043282182ded22808a4b87839be03515a89370105f5a402c002b0003020304000d0018001604030503060302030804080508060401050106010201002d00020101001c00024001003900580901100c000704801000000801100e01080b01140104800075306ab20005048010000080ff73db10000000011aea9aaa709a50c400000001c0000000ff02de1a0243e80604801000000408ffffffffffffffff2001000f00001500e1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0s  4ms TRACE [epoch 0 Write] encrypt ct=a1619c88c958c5f309c2aacf9540d5a454b74c58960196cd0974f6758c7f59e0bcac67b1fe134eb5b8ed7699300135ff77d10af0ec3c597241887b70996412575eb760e08a76667e5cd9d246d4ad84b3072b33ed58c1b9aee2fdd5771813f0b5ed0b1d44c60b8a79db21c6ef5dfc9061c66c1415335040bf3666ce7d1d77dd2ecba54d87e4fe6109a9d0d9fe41a5ab305a26cfa1d279c862e72ab4eab97b6eb23db1341534b8404a6dc3959e6d6ca66fc438ecbeecd68ce0470556eb53d9ed0da78877f95e61682a2fbd831c51ee1e6b6eda38837a0bd61f884ae3d147408ab0bfce2cca858c527c631c8201ed7a369b60d8fb3902748b262d353db1dea600399b48cdde82a8c2181f3b7da3a740c66fba40cfb14bbcae6fd3aab6bbcb026a0096fb4eb6be4241aa719c8eff3bb7147adb61b673b717de5a6473dc297c36651f0e90a967cd40c1e067722bf67694239e1f2489cbd5595040ea7f4dd8c461747a3d804d6b0d80781fb34edb4d5ae295fb1e01ec3cf28940e5c86c0429ccba04f6ff48e1fbb0f8d2b727597741badc16fbeb8af9804e93bb22fd4478b8329855a22c373429d317070a0bb47b08d865ca3284c4d51b82b3bf1f4a86460cace6496f027cb3174abd68942b6e744c227830a5c99dc9e0914e84cc443d97fefa5206c5becd5023dca0aea08fe0ef9f65f7b1301a671f1a3357cd8012e919b314f3b5af4330f6e9a1d66d414f33a9562a158891b75e0f17
0s  4ms TRACE [epoch 0 Write] HP sample=88c958c5f309c2aacf9540d5a454b74c mask=a1472ee48bdf945da52cfc9a2caab1ec
0s  4ms TRACE Packet built c1000000010884ba35f9a68da93d0000421547a1619c88c958c5f309c2aacf9540d5a454b74c58960196cd0974f6758c7f59e0bcac67b1fe134eb5b8ed7699300135ff77d10af0ec3c597241887b70996412575eb760e08a76667e5cd9d246d4ad84b3072b33ed58c1b9aee2fdd5771813f0b5ed0b1d44c60b8a79db21c6ef5dfc9061c66c1415335040bf3666ce7d1d77dd2ecba54d87e4fe6109a9d0d9fe41a5ab305a26cfa1d279c862e72ab4eab97b6eb23db1341534b8404a6dc3959e6d6ca66fc438ecbeecd68ce0470556eb53d9ed0da78877f95e61682a2fbd831c51ee1e6b6eda38837a0bd61f884ae3d147408ab0bfce2cca858c527c631c8201ed7a369b60d8fb3902748b262d353db1dea600399b48cdde82a8c2181f3b7da3a740c66fba40cfb14bbcae6fd3aab6bbcb026a0096fb4eb6be4241aa719c8eff3bb7147adb61b673b717de5a6473dc297c36651f0e90a967cd40c1e067722bf67694239e1f2489cbd5595040ea7f4dd8c461747a3d804d6b0d80781fb34edb4d5ae295fb1e01ec3cf28940e5c86c0429ccba04f6ff48e1fbb0f8d2b727597741badc16fbeb8af9804e93bb22fd4478b8329855a22c373429d317070a0bb47b08d865ca3284c4d51b82b3bf1f4a86460cace6496f027cb3174abd68942b6e744c227830a5c99dc9e0914e84cc443d97fefa5206c5becd5023dca0aea08fe0ef9f65f7b1301a671f1a3357cd8012e919b314f3b5af4330f6e9a1d66d414f33a9562a158891b75e0f17
0s  4ms DEBUG [Client 84ba35f9a68da93d] pad Initial to path MTU 1357
0s  5ms DEBUG [LossRecovery] packet in-0 sent
0s  5ms TRACE [Pacer 2714/1357] spend 1357 over 13370, 100ms
0s  5ms DEBUG [NewReno CongCtrl 1357/13370 ssthresh 18446744073709551615] Pkt Sent len 1357, bif 1357, cwnd 13370
0s  5ms TRACE [Http3 client] Process http3 internal.
0s  5ms TRACE [Http3 client] Check connection events.
0s  5ms DEBUG [Http3 client] check_connection_events - event StateChange(WaitInitial).
0s  5ms DEBUG [Http3 connection] Handle state change WaitInitial
0s  5ms TRACE [Http3 client] Process output.
0s  5ms TRACE [Http3 client] Process http3 internal.
0s  5ms TRACE [Http3 client] Check connection events.
0s  5ms TRACE [Client 84ba35f9a68da93d] process_output WaitInitial Instant { tv_sec: 877638, tv_nsec: 512799091 }
0s  5ms TRACE [LossRecovery] timeout Instant { tv_sec: 877638, tv_nsec: 512799091 }
0s  5ms TRACE detect lost ap: now=Instant { tv_sec: 877638, tv_nsec: 512799091 } delay=112.5ms
0s  5ms TRACE detect lost hs: now=Instant { tv_sec: 877638, tv_nsec: 512799091 } delay=112.5ms
0s  6ms TRACE detect lost in: now=Instant { tv_sec: 877638, tv_nsec: 512799091 } delay=112.5ms
0s  6ms TRACE [Client 84ba35f9a68da93d] output Instant { tv_sec: 877638, tv_nsec: 512799091 }
0s  6ms DEBUG [LossRecovery] get send profile Instant { tv_sec: 877638, tv_nsec: 512799091 }
0s  6ms TRACE [Pacer 1749/1357] next 13370/100ms no wait = Instant { tv_sec: 877638, tv_nsec: 508500465 }
0s  6ms DEBUG [Client 84ba35f9a68da93d] output_path send_profile SendProfile { limit: 1357, pto: None, probe: (), paced: false }
0s  6ms DEBUG Building Initial dcid 84ba35f9a68da93d scid
0s  6ms TRACE [Client 84ba35f9a68da93d] Get callback delay Instant { tv_sec: 877638, tv_nsec: 512799091 }
0s  6ms TRACE ack_time for ap = None
0s  6ms TRACE ack_time for hs = None
0s  6ms TRACE ack_time for in = None
0s  6ms TRACE [Client 84ba35f9a68da93d] Idle/keepalive timer Instant { tv_sec: 877668, tv_nsec: 508500465 }
0s  6ms TRACE [LossRecovery] next_timeout loss=None pto=Some(Instant { tv_sec: 877638, tv_nsec: 808500465 })
0s  6ms TRACE [Client 84ba35f9a68da93d] Loss recovery timer Instant { tv_sec: 877638, tv_nsec: 808500465 }
0s  7ms DEBUG [Client 84ba35f9a68da93d] delay duration 295.701374ms
0s  7ms TRACE [Http3 client] Process http3 internal.
0s  7ms TRACE [Http3 client] Check connection events.
0s  7ms TRACE [Http3 client] Process input.
0s  7ms TRACE [Client 84ba35f9a68da93d] pri-path:84ba35f9a68da93d 0.0.0.0:46978->172.17.0.3:4433 input c7000000010008de2f194a57591ff700402716892b0450c9d0bfb090f1f3f7df2ab01f593b31c69bf0c947a2c168cc24256a80411ec63e4aad
0s  7ms TRACE [Client 84ba35f9a68da93d] Received unverified packet Initial: [18]: c7000000010008de2f194a57591ff7004027 [39]: 16892b0450c9d0bfb090f1f3f7df2ab01f593b31c69bf0c947a2c168cc24256a80411ec63e4aad
0s  7ms TRACE unmask hdr=c7000000010008de2f194a57591ff700402716892b04
0s  7ms TRACE [epoch 0 Read] HP sample=50c9d0bfb090f1f3f7df2ab01f593b31 mask=f7164d5e4c9701f8732f6e3a6be11656
0s  7ms TRACE unmasked hdr=c0000000010008de2f194a57591ff700402700
0s  7ms TRACE [epoch 0 Read] decoded header: [192, 0, 0, 0, 1, 0, 8, 222, 47, 25, 74, 87, 89, 31, 247, 0, 64, 39, 0]
0s  7ms TRACE [epoch 0 Read] decrypt pn=0 hdr=c0000000010008de2f194a57591ff700402700 body=892b0450c9d0bfb090f1f3f7df2ab01f593b31c69bf0c947a2c168cc24256a80411ec63e4aad
0s  7ms DEBUG [Client 84ba35f9a68da93d] pn=0 type=Initial pri-path:84ba35f9a68da93d 0.0.0.0:46978->172.17.0.3:4433
  -> RX Ack { largest_acknowledged: 0, ack_delay: 55, first_ack_range: 0, ack_ranges: [] }
  -> RX ConnectionClose { error_code: Transport(336), frame_type: 0, reason_phrase: [84, 76, 83, 32, 97, 108, 101, 114, 116, 32, 56, 48] }
0s  7ms INFO [Client 84ba35f9a68da93d] Rx ACK space=in, ranges=[0..=0]
0s  7ms DEBUG [LossRecovery] ACK for in - largest_acked=0.
0s  7ms TRACE remove_packet outstanding == 0 for space in
0s  8ms TRACE RTT latest=6.075183ms -> estimate=6.075183ms~3.037591ms
0s  8ms TRACE detect lost in: now=Instant { tv_sec: 877638, tv_nsec: 514575648 } delay=6.83458ms
0s  8ms TRACE [NewReno CongCtrl 1357/13370 ssthresh 18446744073709551615] app limited=true, bytes_in_flight:1357, cwnd: 13370, state: SlowStart pacing_burst_size: 2674
0s  8ms INFO Acked crypto frame space=in offset=0 length=512
0s  8ms INFO [Client 84ba35f9a68da93d] ConnectionClose received. Error code: Transport(336) frame type 0 reason TLS alert 80
0s  8ms INFO [Client 84ba35f9a68da93d] State change from WaitInitial -> Draining { error: Transport(PeerError(336)), timeout: Instant { tv_sec: 877638, tv_nsec: 644252289 } }
0s  8ms DEBUG [Recvd-in] received 0, next: 0
0s  8ms TRACE [Http3 client] Process http3 internal.
0s  8ms TRACE [Http3 client] Check connection events.
0s  8ms DEBUG [Http3 client] check_connection_events - event StateChange(Draining { error: Transport(PeerError(336)), timeout: Instant { tv_sec: 877638, tv_nsec: 644252289 } }).
0s  8ms DEBUG [Http3 connection] Handle state change Draining { error: Transport(PeerError(336)), timeout: Instant { tv_sec: 877638, tv_nsec: 644252289 } }
0s  8ms INFO [Http3 connection] Fetch method=GET target: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv4(172.17.0.3)), port: Some(4433), path: "/10m4.txt", query: None, fragment: None }
thread 'main' panicked at 'Can't create stream HTTP/3 error: AlreadyClosed', neqo-client/src/main.rs:501:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: neqo_client::Handler::download_next
             at ./neqo-client/src/main.rs:501:17
   3: neqo_client::Handler::download_urls
             at ./neqo-client/src/main.rs:457:17
   4: neqo_client::Handler::maybe_key_update
             at ./neqo-client/src/main.rs:508:9
   5: neqo_client::process_loop
             at ./neqo-client/src/main.rs:432:21
   6: neqo_client::client
             at ./neqo-client/src/main.rs:678:5
   7: neqo_client::main
             at ./neqo-client/src/main.rs:843:17
   8: core::ops::function::FnOnce::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
0s 23ms TRACE [AgentIo] take output
```

**Comment by martinthomson** [comment]
Interesting.  This is a bug in our (dodgy) client only to the extent that we keep trying to make requests after the server drops the connection.

The real cause of this is that lsquic has sent us a TLS internal_error alert.  That is reserved for cases where your TLS stack is busted, so we probably hit a bug in their server.

If you want to talk to the developers of lsquic, they hang out on the quicdev.slack.com slack.

**Comment by feters** [comment]
Okay, I will open an issue on lsquic github regarding this issue.

I did send a request to join quicdev.slack.com to quic-chairs@ietf.org twice on the 1st of Feb and 11th of March but still haven't got any reply.
