### ISSUE TITLE
Intermittent test failure 

### ISSUE THREAD

**Issue by mb** [mozilla/neqo#1477]
Intermittent test failure from last week in CI: [logs_568.zip](https://github.com/mozilla/neqo/files/13114183/logs_568.zip)

`less -r '2_Neqo Build and Test (1.65.0).txt'` Maybe related to [Bug 1855167](https://bugzilla.mozilla.org/show_bug.cgi?id=1855167)

<details>

```
2023-10-17T16:33:34.3077195Z 0s456ms DEBUG [Client ea0bf036871e209a] output_path send_profile SendProfile { limit: 1292, pto: None, probe: (), paced: false }
2023-10-17T16:33:34.3077405Z 0s456ms DEBUG Building Short dcid 080000000020d49c
2023-10-17T16:33:34.3077584Z 0s456ms DEBUG processing streams...  unfair:
2023-10-17T16:33:34.3077716Z 0s456ms DEBUG    SendStream 2
2023-10-17T16:33:34.3077855Z 0s456ms DEBUG fair streams:
2023-10-17T16:33:34.3078025Z 0s456ms DEBUG processing streams...  unfair:
2023-10-17T16:33:34.3078157Z 0s456ms DEBUG    SendStream 2
2023-10-17T16:33:34.3078297Z 0s456ms DEBUG fair streams:
2023-10-17T16:33:34.3078465Z 0s456ms DEBUG processing streams...  unfair:
2023-10-17T16:33:34.3078594Z 0s456ms DEBUG    SendStream 2
2023-10-17T16:33:34.3078735Z 0s456ms DEBUG fair streams:
2023-10-17T16:33:34.3079454Z 0s456ms DEBUG [Client ea0bf036871e209a] pn=197 type=Short pri-path:080000000020d49c [fe80::1]:443->[fe80::1]:443
2023-10-17T16:33:34.3079828Z   TX -> Stream { stream_id: 2, offset: 241833, len: >>1260, fin: false }
2023-10-17T16:33:34.3080092Z 0s456ms DEBUG [LossRecovery] packet ap-197 sent
2023-10-17T16:33:34.3080568Z 0s456ms DEBUG [NewReno CongCtrl 54470/54470 ssthresh 54470] Pkt Sent len 1292, bif 54470, cwnd 54470
2023-10-17T16:33:34.3080986Z 0s456ms DEBUG [LossRecovery] get send profile Instant { tv_sec: 808, tv_nsec: 578520716 }
2023-10-17T16:33:34.3081736Z 0s456ms DEBUG [Server ea0bf036871e209a] output_path send_profile SendProfile { limit: 1337, pto: None, probe: (), paced: false }
2023-10-17T16:33:34.3081931Z 0s456ms DEBUG Building Short dcid 08000000009f00e6
2023-10-17T16:33:34.3082119Z 0s456ms DEBUG processing streams...  unfair:
2023-10-17T16:33:34.3082247Z 0s456ms DEBUG fair streams:
2023-10-17T16:33:34.3082418Z 0s456ms DEBUG processing streams...  unfair:
2023-10-17T16:33:34.3082563Z 0s456ms DEBUG fair streams:
2023-10-17T16:33:34.3082732Z 0s456ms DEBUG processing streams...  unfair:
2023-10-17T16:33:34.3082859Z 0s456ms DEBUG fair streams:
2023-10-17T16:33:34.3083045Z 0s456ms DEBUG processing streams...  unfair:
2023-10-17T16:33:34.3083172Z 0s456ms DEBUG fair streams:
2023-10-17T16:33:34.3083339Z 0s456ms DEBUG processing streams...  unfair:
2023-10-17T16:33:34.3083547Z 0s456ms DEBUG fair streams:
2023-10-17T16:33:34.3083835Z 0s456ms DEBUG [Server ea0bf036871e209a] delay duration 576.080508ms
2023-10-17T16:33:34.3084246Z 0s456ms DEBUG [LossRecovery] get send profile Instant { tv_sec: 808, tv_nsec: 578520716 }
2023-10-17T16:33:34.3084879Z 0s456ms DEBUG [Client ea0bf036871e209a] output_path send_profile SendProfile { limit: 255, pto: None, probe: (), paced: false }
2023-10-17T16:33:34.3085073Z 0s456ms DEBUG Building Short dcid 080000000020d49c
2023-10-17T16:33:34.3085369Z 0s456ms DEBUG [Client ea0bf036871e209a] delay duration 112.589001ms
2023-10-17T16:33:34.3085781Z 0s456ms DEBUG [LossRecovery] get send profile Instant { tv_sec: 808, tv_nsec: 578520716 }
2023-10-17T16:33:34.3086417Z 0s456ms DEBUG [Server ea0bf036871e209a] output_path send_profile SendProfile { limit: 1337, pto: None, probe: (), paced: false }
2023-10-17T16:33:34.3086632Z 0s456ms DEBUG Building Short dcid 08000000009f00e6
2023-10-17T16:33:34.3086804Z 0s456ms DEBUG processing streams...  unfair:
2023-10-17T16:33:34.3086934Z 0s456ms DEBUG fair streams:
2023-10-17T16:33:34.3087119Z 0s456ms DEBUG processing streams...  unfair:
2023-10-17T16:33:34.3087244Z 0s456ms DEBUG fair streams:
2023-10-17T16:33:34.3087413Z 0s456ms DEBUG processing streams...  unfair:
2023-10-17T16:33:34.3087555Z 0s456ms DEBUG fair streams:
2023-10-17T16:33:34.3087721Z 0s456ms DEBUG processing streams...  unfair:
2023-10-17T16:33:34.3087858Z 0s456ms DEBUG fair streams:
2023-10-17T16:33:34.3088023Z 0s456ms DEBUG processing streams...  unfair:
2023-10-17T16:33:34.3088146Z 0s456ms DEBUG fair streams:
2023-10-17T16:33:34.3088568Z 0s456ms DEBUG [Server ea0bf036871e209a] delay duration 576.080508ms
2023-10-17T16:33:34.3088981Z 0s456ms DEBUG [LossRecovery] get send profile Instant { tv_sec: 808, tv_nsec: 580160447 }
2023-10-17T16:33:34.3089606Z 0s456ms DEBUG [Client ea0bf036871e209a] output_path send_profile SendProfile { limit: 255, pto: None, probe: (), paced: false }
2023-10-17T16:33:34.3089876Z 0s456ms DEBUG Building Short dcid 080000000020d49c
2023-10-17T16:33:34.3090162Z 0s456ms DEBUG [Client ea0bf036871e209a] delay duration 110.94927ms
2023-10-17T16:33:34.3090879Z 0s456ms DEBUG [Server ea0bf036871e209a] pn=155 type=Short pri-path:08000000009f00e6 [fe80::1]:443->[fe80::1]:443
2023-10-17T16:33:34.3091754Z   -> RX Ack { largest_acknowledged: 84, ack_delay: 158, first_ack_range: 0, ack_ranges: [AckRange { gap: 0, range: 0 }, AckRange { gap: 0, range: 79 }] }
2023-10-17T16:33:34.3092156Z 0s456ms INFO [Server ea0bf036871e209a] Rx ACK space=ap, ranges=[84..=84, 82..=82, 1..=80]
2023-10-17T16:33:34.3092487Z 0s456ms DEBUG [LossRecovery] ACK for ap - largest_acked=84.
2023-10-17T16:33:34.3092864Z 0s456ms DEBUG [NewReno CongCtrl 29/13370 ssthresh 18446744073709551615] Pkts lost 2
2023-10-17T16:33:34.3093457Z 0s456ms INFO [NewReno CongCtrl 29/6685 ssthresh 6685] Cong event -> recovery; cwnd 6685, ssthresh 6685
2023-10-17T16:33:34.3093895Z 0s456ms DEBUG [NewReno CongCtrl 29/6685 ssthresh 6685] state -> RecoveryStart
2023-10-17T16:33:34.3094147Z 0s457ms DEBUG [Server ea0bf036871e209a] Lost: HandshakeDone
2023-10-17T16:33:34.3095126Z 0s457ms DEBUG [Server ea0bf036871e209a] Lost: NewConnectionId(ConnectionIdEntry { seqno: 1, cid: CID [9]: 090000000102fcc278, srt: [29, 99, 159, 98, 139, 33, 155, 139, 143, 172, 178, 73, 7, 11, 190, 180] })
2023-10-17T16:33:34.3096159Z 0s457ms DEBUG [Server ea0bf036871e209a] Lost: NewConnectionId(ConnectionIdEntry { seqno: 2, cid: CID [14]: 0e00000002b7c38da6ce22648400, srt: [12, 115, 82, 0, 172, 86, 66, 94, 216, 146, 89, 234, 85, 111, 166, 97] })0-17T16:33:34.3097199Z 0s457ms DEBUG [Server ea0bf036871e209a] Lost: NewConnectionId(ConnectionIdEntry { seqno: 3, cid: CID [13]: 0d00000003c1a1b97db3718e20, srt: [178, 18, 255, 53, 179, 19, 229, 217, 91, 139, 233, 188, 67, 171, 123, 177] })7T16:33:34.3098244Z 0s457ms DEBUG [Server ea0bf036871e209a] Lost: NewConnectionId(ConnectionIdEntry { seqno: 4, cid: CID [13]: 0d000000041d4c978caac69a05, srt: [140, 52, 67, 151, 101, 90, 122, 197, 183, 97, 40, 74, 232, 111, 171, 150] })17T16:33:34.3099275Z 0s457ms DEBUG [Server ea0bf036871e209a] Lost: NewConnectionId(ConnectionIdEntry { seqno: 5, cid: CID [8]: 08000000059637d3, srt: [107, 98, 60, 116, 167, 90, 201, 238, 6, 135, 224, 128, 129, 133, 147, 170] })
2023-10-17T16:33:34.3100275Z 0s457ms DEBUG [Server ea0bf036871e209a] Lost: NewConnectionId(ConnectionIdEntry { seqno: 6, cid: CID [11]: 0b0000000680d41ca5395c, srt: [30, 22, 6, 161, 176, 162, 75, 15, 242, 110, 197, 19, 21, 171, 2, 133] })
2023-10-17T16:33:34.3101265Z 0s457ms DEBUG [Server ea0bf036871e209a] Lost: NewConnectionId(ConnectionIdEntry { seqno: 7, cid: CID [8]: 08000000073c44f0, srt: [215, 119, 60, 218, 234, 246, 49, 207, 198, 28, 157, 152, 83, 170, 221, 125] })
2023-10-17T16:33:34.3101742Z 0s457ms DEBUG [Server ea0bf036871e209a] Lost: AckFrequency(AckRate { packets: 1, delay: 4.16346ms })
2023-10-17T16:33:34.3102002Z 0s457ms DEBUG [Server ea0bf036871e209a] Lost: HandshakeDone
2023-10-17T16:33:34.3102773Z thread 'transfer_delay_drop' panicked at 'StateSignaling must be in Idle state.', neqo-transport/src/connection/state.rs:206:13
2023-10-17T16:33:34.3102911Z stack backtrace:
2023-10-17T16:33:34.3103056Z    0: std::panicking::begin_panic
2023-10-17T16:33:34.3103490Z              at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:616:12
2023-10-17T16:33:34.3103806Z    1: neqo_transport::connection::state::StateSignaling::handshake_done
2023-10-17T16:33:34.3103975Z              at ./src/connection/state.rs:206:13
2023-10-17T16:33:34.3104244Z    2: neqo_transport::connection::Connection::handle_lost_packets
2023-10-17T16:33:34.3104516Z              at ./src/connection/mod.rs:2760:53
2023-10-17T16:33:34.3104740Z    3: neqo_transport::connection::Connection::handle_ack
2023-10-17T16:33:34.3104919Z              at ./src/connection/mod.rs:2828:9
2023-10-17T16:33:34.3105193Z    4: neqo_transport::connection::Connection::input_frame
2023-10-17T16:33:34.3105356Z              at ./src/connection/mod.rs:2616:17
2023-10-17T16:33:34.3105612Z    5: neqo_transport::connection::Connection::process_packet
2023-10-17T16:33:34.3105774Z              at ./src/connection/mod.rs:1500:29
2023-10-17T16:33:34.3105995Z    6: neqo_transport::connection::Connection::input_path
2023-10-17T16:33:34.3106173Z              at ./src/connection/mod.rs:1419:31
2023-10-17T16:33:34.3106370Z    7: neqo_transport::connection::Connection::input
2023-10-17T16:33:34.3106532Z              at ./src/connection/mod.rs:1368:19
2023-10-17T16:33:34.3106749Z    8: neqo_transport::connection::Connection::process
2023-10-17T16:33:34.3106911Z              at ./src/connection/mod.rs:1025:13
2023-10-17T16:33:34.3107267Z    9: <network::sim::connection::ConnectionNode as network::sim::Node>::process
2023-10-17T16:33:34.3107434Z              at ./tests/sim/connection.rs:123:23
2023-10-17T16:33:34.3107577Z   10: network::sim::Simulator::run
2023-10-17T16:33:34.3107737Z              at ./tests/sim/mod.rs:187:27
2023-10-17T16:33:34.3107879Z   11: network::transfer_delay_drop
2023-10-17T16:33:34.3108025Z              at ./tests/sim/mod.rs:71:13
2023-10-17T16:33:34.3108221Z   12: network::transfer_delay_drop::{{closure}}
2023-10-17T16:33:34.3108360Z              at ./tests/sim/mod.rs:60:9
2023-10-17T16:33:34.3108531Z   13: core::ops::function::FnOnce::call_once
2023-10-17T16:33:34.3108980Z              at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
2023-10-17T16:33:34.3109146Z   14: core::ops::function::FnOnce::call_once
2023-10-17T16:33:34.3109595Z              at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
2023-10-17T16:33:34.3110009Z note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
2023-10-17T16:33:34.3110024Z 
2023-10-17T16:33:34.3110030Z 
2023-10-17T16:33:34.3110138Z failures:
2023-10-17T16:33:34.3110280Z     transfer_delay_drop
2023-10-17T16:33:34.3110286Z 
2023-10-17T16:33:34.3110757Z test result: FAILED. 10 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 2.64s
```
</details>

**Comment by larseggert** [comment]
@mb is this still happening?

**Comment by larseggert** [comment]
Can we try and write a test case for it?

**Comment by larseggert** [comment]
I think this was fixed by #1882.
