### ISSUE TITLE
Test failures when running `cargo test --release`

### ISSUE THREAD

**Issue by mb** [mozilla/neqo#1481]
Probably worth investigating and fixing.

```
failures:
    connection::tests::ackrate::migrate_ack_delay
    connection::tests::cc::cc_slow_start_to_cong_avoidance_recovery_period
    connection::tests::handshake::reorder_1rtt
    connection::tests::migration::migrate_immediate
    connection::tests::migration::migrate_immediate_fail
    connection::tests::migration::migrate_rtt
    connection::tests::migration::migration_client_empty_cid
    connection::tests::migration::migration_graceful
    connection::tests::migration::path_forwarding_attack
    connection::tests::migration::retire_all
    connection::tests::migration::retire_prior_to_migration_failure
    connection::tests::migration::retire_prior_to_migration_success
    connection::tests::priority::high_normal
    connection::tests::zerortt::zero_rtt_send_recv

test result: FAILED. 436 passed; 14 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.12s
```

<details>

```

failures:

---- connection::tests::ackrate::migrate_ack_delay stdout ----
thread 'connection::tests::ackrate::migrate_ack_delay' panicked at neqo-transport/src/connection/tests/ackrate.rs:155:10:
called `Result::unwrap()` on an `Err` value: InvalidMigration

---- connection::tests::cc::cc_slow_start_to_cong_avoidance_recovery_period stdout ----
thread 'connection::tests::cc::cc_slow_start_to_cong_avoidance_recovery_period' panicked at neqo-transport/src/connection/tests/cc.rs:62:5:
assertion `left == right` failed
  left: 12
 right: 13

---- connection::tests::handshake::reorder_1rtt stdout ----
thread 'connection::tests::handshake::reorder_1rtt' panicked at neqo-transport/src/connection/tests/handshake.rs:573:5:
assertion `left == right` failed
  left: 11
 right: 12

---- connection::tests::migration::migrate_rtt stdout ----
thread 'connection::tests::migration::migrate_rtt' panicked at neqo-transport/src/connection/tests/migration.rs:224:10:
called `Result::unwrap()` on an `Err` value: InvalidMigration

---- connection::tests::migration::migrate_immediate stdout ----
thread 'connection::tests::migration::migrate_immediate' panicked at neqo-transport/src/connection/tests/migration.rs:184:10:
called `Result::unwrap()` on an `Err` value: InvalidMigration

---- connection::tests::migration::migration_graceful stdout ----
thread 'connection::tests::migration::migration_graceful' panicked at neqo-transport/src/connection/tests/migration.rs:370:10:
called `Result::unwrap()` on an `Err` value: InvalidMigration

---- connection::tests::migration::path_forwarding_attack stdout ----
thread 'connection::tests::migration::path_forwarding_attack' panicked at neqo-transport/src/connection/tests/migration.rs:108:56:
called `Option::unwrap()` on a `None` value

---- connection::tests::migration::migrate_immediate_fail stdout ----
thread 'connection::tests::migration::migrate_immediate_fail' panicked at neqo-transport/src/connection/tests/migration.rs:240:10:
called `Result::unwrap()` on an `Err` value: InvalidMigration

---- connection::tests::migration::migration_client_empty_cid stdout ----
thread 'connection::tests::migration::migration_client_empty_cid' panicked at neqo-transport/src/connection/tests/migration.rs:370:10:
called `Result::unwrap()` on an `Err` value: InvalidMigration

---- connection::tests::migration::retire_prior_to_migration_success stdout ----
thread 'connection::tests::migration::retire_prior_to_migration_success' panicked at neqo-transport/src/connection/tests/migration.rs:912:10:
called `Result::unwrap()` on an `Err` value: InvalidMigration

---- connection::tests::migration::retire_prior_to_migration_failure stdout ----
thread 'connection::tests::migration::retire_prior_to_migration_failure' panicked at neqo-transport/src/connection/tests/migration.rs:857:10:
called `Result::unwrap()` on an `Err` value: InvalidMigration

---- connection::tests::priority::high_normal stdout ----
thread 'connection::tests::priority::high_normal' panicked at neqo-transport/src/connection/tests/priority.rs:356:5:
assertion `left != right` failed
  left: 0
 right: 0

---- connection::tests::migration::retire_all stdout ----
thread 'connection::tests::migration::retire_all' panicked at neqo-transport/src/connection/tests/migration.rs:829:5:
assertion `left == right` failed
  left: 1
 right: 8

---- connection::tests::zerortt::zero_rtt_send_recv stdout ----
thread 'connection::tests::zerortt::zero_rtt_send_recv' panicked at neqo-transport/src/connection/tests/zerortt.rs:71:5:
assertion failed: server_process_0rtt.as_dgram_ref().is_some()


failures:
    connection::tests::ackrate::migrate_ack_delay
    connection::tests::cc::cc_slow_start_to_cong_avoidance_recovery_period
    connection::tests::handshake::reorder_1rtt
    connection::tests::migration::migrate_immediate
    connection::tests::migration::migrate_immediate_fail
    connection::tests::migration::migrate_rtt
    connection::tests::migration::migration_client_empty_cid
    connection::tests::migration::migration_graceful
    connection::tests::migration::path_forwarding_attack
    connection::tests::migration::retire_all
    connection::tests::migration::retire_prior_to_migration_failure
    connection::tests::migration::retire_prior_to_migration_success
    connection::tests::priority::high_normal
    connection::tests::zerortt::zero_rtt_send_recv

test result: FAILED. 436 passed; 14 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.12s

error: test failed, to rerun pass `-p neqo-transport --lib`
```

**Comment by larseggert** [comment]
This is pretty odd. These should not fail. We should probably fix this and then add a release test run to CI.
