### ISSUE TITLE
Client aborts when doing v2 w/o version negotiation

### ISSUE THREAD

**Issue by larseggert** [mozilla/neqo#1516]
On PR #1515, doing `env RUST_LOG=debug DYLD_LIBRARY_PATH="$NSS_DIR/../dist/Debug/lib" SSLKEYLOGFILE=sslkeylog target/debug/neqo-client -V 6b3343cf https://www.haproxy.org` dies with
```
...
0s114ms INFO [Client 4959a3ce8a8a3b98] validate_versions: missing extension
0s114ms INFO [Client 4959a3ce8a8a3b98] State change from Handshaking -> Closing { error: Transport(VersionNegotiation), timeout: Instant { tv_sec: 148737, tv_nsec: 956123128 } }
0s114ms DEBUG [pri-path:073a0a65afebbd8a [::]:52758->[2001:bc8:35ee:100::1]:443] Path validated Instant { tv_sec: 148737, tv_nsec: 323845000 }
0s114ms WARN [Client 4959a3ce8a8a3b98] Closing again after error Transport(VersionNegotiation)
0s114ms DEBUG [Http3 client] check_connection_events - event StateChange(Closing { error: Transport(VersionNegotiation), timeout: Instant { tv_sec: 148737, tv_nsec: 956123128 } }).
0s114ms DEBUG [Http3 connection] Handle state change Closing { error: Transport(VersionNegotiation), timeout: Instant { tv_sec: 148737, tv_nsec: 956123128 } }
0s114ms INFO [Http3 connection] Fetch method=GET target: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("www.haproxy.org")), port: None, path: "/", query: None, fragment: None }
thread 'main' panicked at neqo-client/src/main.rs:507:17:
Can't create stream HTTP/3 error: AlreadyClosed
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14
   2: neqo_client::Handler::download_next
             at ./neqo-client/src/main.rs:507:17
   3: neqo_client::Handler::download_urls
             at ./neqo-client/src/main.rs:464:17
   4: neqo_client::Handler::maybe_key_update
             at ./neqo-client/src/main.rs:514:9
   5: neqo_client::process_loop
             at ./neqo-client/src/main.rs:439:21
   6: neqo_client::client
             at ./neqo-client/src/main.rs:684:5
   7: neqo_client::main
             at ./neqo-client/src/main.rs:850:17
   8: core::ops::function::FnOnce::call_once
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I am guessing the check in `neqo-transport/src/connection/mod.rs:2502` is incorrect, because it seems to assume v2 can only be used after version negotiation, which is untrue.

**Comment by martinthomson** [comment]
If you negotiate v2, you need to include the version negotiation transport parameter.  It looks like haproxy isn't.  Or - perhaps more likely - we are looking for the wrong extension codepoint because we haven't been updated with the latest RFC numbers their either.

**Comment by larseggert** [comment]
But I'm not negotiating v2 - I am telling the client to use that version from the beginning.

**Comment by martinthomson** [comment]
Sure.  You won't be getting a VN packet, but the extension is a mandatory part of implementing v2.

**Comment by larseggert** [comment]
You're right - the transport parameter was renumbered.
