### ISSUE TITLE
having trouble building neqo-crypto via cargo

### ISSUE THREAD

**Issue by i3roly** [mozilla/neqo#1918]
hello,

my build keeps failing even though i installed nspr/nss via macports and also gyp.

i have used

```
export NSS_DIR=/opt/local/lib/nss
export NSPR_DIR=/opt/local/lib/nspr
export NSS_TARGET=x86_64
```

and it keeps crying about missing headers:

```
^[[A^[[AGagansMacPro:neqo Gagan$ cargo build
   Compiling proc-macro2 v1.0.84
   Compiling unicode-ident v1.0.12
   Compiling libc v0.2.155
   Compiling autocfg v1.3.0
   Compiling serde v1.0.203
   Compiling fnv v1.0.7
   Compiling strsim v0.11.1
   Compiling ident_case v1.0.1
   Compiling memchr v2.7.2
   Compiling glob v0.3.1
   Compiling lazy_static v1.4.0
   Compiling cfg-if v1.0.0
   Compiling regex-syntax v0.8.3
   Compiling hashbrown v0.14.5
   Compiling minimal-lexical v0.2.1
   Compiling equivalent v1.0.1
   Compiling itoa v1.0.11
   Compiling log v0.4.21
   Compiling bindgen v0.69.4
   Compiling lazycell v1.3.0
   Compiling either v1.12.0
   Compiling serde_json v1.0.117
   Compiling bitflags v2.5.0
   Compiling ryu v1.0.18
   Compiling libloading v0.8.3
   Compiling shlex v1.3.0
   Compiling version_check v0.9.4
   Compiling rustc-hash v1.1.0
   Compiling powerfmt v0.2.0
   Compiling time-core v0.1.2
   Compiling num-conv v0.1.0
   Compiling neqo-common v0.6.9 (/Users/Gagan/Downloads/mozilla-unified/neqo/neqo-common)
   Compiling tinyvec_macros v0.1.1
   Compiling hashbrown v0.12.3
   Compiling tinyvec v1.6.0
   Compiling syn v1.0.109
   Compiling rust_decimal v1.35.0
   Compiling env_logger v0.10.2
   Compiling itertools v0.12.1
   Compiling arrayvec v0.7.4
   Compiling deranged v0.3.11
   Compiling unicode-bidi v0.3.15
   Compiling percent-encoding v2.3.1
   Compiling static_assertions v1.1.0
   Compiling data-encoding v2.6.0
   Compiling unicode-width v0.1.12
   Compiling unicode-segmentation v1.11.0
   Compiling form_urlencoded v1.2.1
   Compiling textwrap v0.11.0
   Compiling ansi_term v0.12.1
   Compiling proc-macro-error-attr v1.0.4
   Compiling indexmap v1.9.3
   Compiling num-traits v0.2.19
   Compiling proc-macro-error v1.0.4
   Compiling slab v0.4.9
   Compiling vec_map v0.8.2
   Compiling strsim v0.8.0
   Compiling clang-sys v1.8.1
   Compiling cfg-if v0.1.10
   Compiling bitflags v1.3.2
   Compiling aho-corasick v1.1.3
   Compiling nom v7.1.3
   Compiling heck v0.3.3
   Compiling quote v1.0.36
   Compiling indexmap v2.2.6
   Compiling atty v0.2.14
   Compiling iovec v0.1.4
   Compiling net2 v0.2.39
   Compiling clap v2.34.0
   Compiling syn v2.0.66
   Compiling mio v0.6.23
   Compiling unicode-normalization v0.1.23
   Compiling time v0.3.36
   Compiling idna v0.5.0
   Compiling mio-extras v2.0.6
   Compiling sfv v0.9.4
   Compiling url v2.5.0
   Compiling regex-automata v0.4.6
   Compiling cexpr v0.6.0
   Compiling structopt-derive v0.4.18
   Compiling darling_core v0.20.9
   Compiling regex v1.10.4
   Compiling structopt v0.3.26
   Compiling serde_derive v1.0.203
   Compiling enum-map-derive v0.17.0
   Compiling enum-map v2.7.3
   Compiling darling_macro v0.20.9
   Compiling darling v0.20.9
   Compiling serde_with_macros v3.8.1
   Compiling enumset_derive v0.8.1
   Compiling enumset v1.1.3
   Compiling smallvec v1.13.2
   Compiling toml v0.5.11
   Compiling serde_with v3.8.1
   Compiling neqo-crypto v0.6.9 (/Users/Gagan/Downloads/mozilla-unified/neqo/neqo-crypto)
   Compiling qlog v0.11.0
error: failed to run custom build command for `neqo-crypto v0.6.9 (/Users/Gagan/Downloads/mozilla-unified/neqo/neqo-crypto)`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/Users/Gagan/Downloads/mozilla-unified/neqo/target/debug/build/neqo-crypto-2766bcaea0f30846/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=NSS_DIR
  cargo:rerun-if-env-changed=NSS_TARGET
  cargo:include=/opt/local/lib/dist/x86_64/include/nspr
  cargo:include=/opt/local/lib/dist/public/nss
  cargo:rustc-link-search=native=/opt/local/lib/dist/x86_64/lib
  cargo:rustc-link-lib=static=certdb
  cargo:rustc-link-lib=static=certhi
  cargo:rustc-link-lib=static=cryptohi
  cargo:rustc-link-lib=static=freebl
  cargo:rustc-link-lib=static=nss_static
  cargo:rustc-link-lib=static=nssb
  cargo:rustc-link-lib=static=nssdev
  cargo:rustc-link-lib=static=nsspki
  cargo:rustc-link-lib=static=nssutil
  cargo:rustc-link-lib=static=pk11wrap
  cargo:rustc-link-lib=static=pkcs12
  cargo:rustc-link-lib=static=pkcs7
  cargo:rustc-link-lib=static=smime
  cargo:rustc-link-lib=static=softokn_static
  cargo:rustc-link-lib=static=ssl
  cargo:rustc-link-lib=dylib=plds4
  cargo:rustc-link-lib=dylib=plc4
  cargo:rustc-link-lib=dylib=nspr4
  cargo:rustc-link-lib=dylib=pthread
  cargo:rustc-link-lib=dylib=dl
  cargo:rustc-link-lib=dylib=c
  cargo:rustc-link-lib=dylib=z
  cargo:rustc-link-lib=dylib=sqlite3
  cargo:rerun-if-changed=bindings/bindings.toml
  cargo:rerun-if-changed=bindings/nspr_error.h

  --- stderr
  Apple LLVM version 10.0.1 (clang-1001.0.46.4)
  Target: x86_64-apple-darwin18.7.0
  Thread model: posix
  InstalledDir: 
  Found CUDA installation: /usr/local/cuda, version 7.0
  ignoring nonexistent directory "/opt/local/lib/dist/x86_64/include/nspr"
  ignoring nonexistent directory "/opt/local/lib/dist/public/nss"
  ignoring nonexistent directory "/opt/intel/tbb/include"
  ignoring nonexistent directory "/usr/include"
  ignoring duplicate directory "/opt/intel/oneapi/mkl/latest/include"
    as it is a non-system directory that duplicates a system directory
  ignoring duplicate directory "/usr/local/include"
  ignoring duplicate directory "/Library/Developer/CommandLineTools/usr/lib/clang/10.0.1/include"
  ignoring duplicate directory "/Library/Developer/CommandLineTools/usr/include"
  #include "..." search starts here:
  #include <...> search starts here:
   /opt/intel/oneapi/mkl/latest/include
   /usr/local/include
   /Library/Developer/CommandLineTools/usr/lib/clang/10.0.1/include
   /Library/Developer/CommandLineTools/usr/include
   /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include
   /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks
   /System/Library/Frameworks (framework directory)
   /Library/Frameworks (framework directory)
  End of search list.
  bindings/nspr_error.h:7:10: fatal error: 'prerror.h' file not found
  thread 'main' panicked at neqo-crypto/build.rs:291:39:
  unable to generate bindings: ClangDiagnostic("bindings/nspr_error.h:7:10: fatal error: 'prerror.h' file not found\n")
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
     1: core::panicking::panic_fmt
               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
     2: core::result::unwrap_failed
               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1652:5
     3: core::result::Result<T,E>::expect
     4: build_script_build::build_bindings
     5: build_script_build::main
     6: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...

```

i also tried

```
cargo add nss --package neqo-crypto
```

so that i could have cargo install nss/nspr before building neqo, but a similar issue arises:

```
GagansMacPro:nss Gagan$ cargo build
   Compiling autocfg v1.3.0
   Compiling memchr v2.7.2
   Compiling regex-syntax v0.8.3
   Compiling lazycell v1.3.0
   Compiling version_check v0.9.4
   Compiling tinyvec_macros v0.1.1
   Compiling rust_decimal v1.35.0
   Compiling syn v1.0.109
   Compiling hashbrown v0.12.3
   Compiling percent-encoding v2.3.1
   Compiling unicode-bidi v0.3.15
   Compiling arrayvec v0.7.4
   Compiling unicode-segmentation v1.11.0
   Compiling data-encoding v2.6.0
   Compiling static_assertions v1.1.0
   Compiling unicode-width v0.1.12
   Compiling strsim v0.8.0
   Compiling cfg-if v0.1.10
   Compiling ansi_term v0.12.1
   Compiling atty v0.2.14
   Compiling bitflags v1.3.2
   Compiling enumset_derive v0.8.1
   Compiling vec_map v0.8.2
   Compiling iovec v0.1.4
   Compiling tinyvec v1.6.0
   Compiling net2 v0.2.39
   Compiling textwrap v0.11.0
   Compiling form_urlencoded v1.2.1
   Compiling clap v2.34.0
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling indexmap v1.9.3
   Compiling num-traits v0.2.19
   Compiling slab v0.4.9
   Compiling heck v0.3.3
   Compiling mio v0.6.23
   Compiling aho-corasick v1.1.3
   Compiling nom v7.1.3
   Compiling enumset v1.1.3
   Compiling unicode-normalization v0.1.23
   Compiling mio-extras v2.0.6
   Compiling idna v0.5.0
   Compiling url v2.5.0
   Compiling sfv v0.9.4
   Compiling regex-automata v0.4.6
   Compiling cexpr v0.6.0
   Compiling structopt-derive v0.4.18
   Compiling structopt v0.3.26
   Compiling regex v1.10.4
   Compiling bindgen v0.69.4
   Compiling neqo-crypto v0.6.9 (/Users/Gagan/Downloads/mozilla-unified/neqo/neqo-crypto)
error: failed to run custom build command for `neqo-crypto v0.6.9 (/Users/Gagan/Downloads/mozilla-unified/neqo/neqo-crypto)`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/Users/Gagan/Downloads/mozilla-unified/neqo/target/debug/build/neqo-crypto-2766bcaea0f30846/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=NSS_DIR
  requesting all changes
  adding changesets
  adding manifests
  adding file changes
  added 16861 changesets with 58624 changes to 10087 files (+104 heads)
  new changesets 9949429068ca:4f28ae03b493
  updating to branch default
  4682 files updated, 0 files merged, 0 files removed, 0 files unresolved
  requesting all changes
  adding changesets
  adding manifests
  adding file changes
  added 4961 changesets with 15926 changes to 983 files (+418 heads)
  new changesets a4b34919bf34:3e25d69ba6b2
  updating to branch default
  611 files updated, 0 files merged, 0 files removed, 0 files unresolved
  NSPR [1/5] configure ...
  NSPR [2/5] make ...
  NSPR [3/5] NOT building tests
  NSPR [4/5] NOT running tests
  NSPR [5/5] install ...

  --- stderr
  ../../../../pr/src/pthreads/ptio.c:2209:21: warning: assigning to 'void *' from 'const void *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
      iov[0].iov_base = buf;
                      ^ ~~~
  ../../../../pr/src/pthreads/ptio.c:2212:60: warning: incompatible pointer types passing 'PRInt32 *' (aka 'int *') to parameter of type 'size_t *' (aka 'unsigned long *') [-Wincompatible-pointer-types]
                            CONNECT_DATA_IDEMPOTENT, iov, 1, &bytes, NULL);
                                                             ^~~~~~
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/socket.h:719:49: note: passing argument to parameter here
      const struct iovec *, unsigned int, size_t *, sae_connid_t *);
                                                  ^
  ../../../../pr/src/pthreads/ptio.c:2211:13: warning: unused variable 'rv' [-Wunused-variable]
      PRInt32 rv = connectx(fd->secret->md.osfd, &endpoints, SAE_ASSOCID_ANY,
              ^
  3 warnings generated.
  /opt/local/bin/ranlib: file: libnspr4.a(pripv6.o) has no symbols
  /opt/local/bin/ranlib: file: libnspr4.a(prmalloc.o) has no symbols
  /opt/local/bin/ranlib: file: libnspr4.a(uxwrap.o) has no symbols
  ranlib: file: libnspr4.a(pripv6.o) has no symbols
  ranlib: file: libnspr4.a(prmalloc.o) has no symbols
  ranlib: file: libnspr4.a(uxwrap.o) has no symbols
  Building NSS requires an installation of gyp: https://gyp.gsrc.io/
  thread 'main' panicked at neqo-crypto/build.rs:169:5:
  NSS build failed
  stack backtrace:
     0:        0x101fb286b - std::backtrace_rs::backtrace::libunwind::trace::h9283b95ff3ea079b
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:        0x101fb286b - std::backtrace_rs::backtrace::trace_unsynchronized::h43b06ae070f7c94c
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:        0x101fb286b - std::sys_common::backtrace::_print_fmt::ha0fdd24cac6a3474
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:67:5
     3:        0x101fb286b - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h65343ad3a85b4e34
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:44:22
     4:        0x101fd5fbb - core::fmt::rt::Argument::fmt::h3ec1454c0b08cc5d
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/rt.rs:138:9
     5:        0x101fd5fbb - core::fmt::write::h11839d3825cb5605
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/mod.rs:1094:21
     6:        0x101faec7e - std::io::Write::write_fmt::h3ab12d369399333c
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/io/mod.rs:1714:15
     7:        0x101fb2649 - std::sys_common::backtrace::_print::ha606478736c0e683
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:47:5
     8:        0x101fb2649 - std::sys_common::backtrace::print::h405f7c76ca12eb27
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:34:9
     9:        0x101fb3de5 - std::panicking::default_hook::{{closure}}::hed87c355606e1822
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:270:22
    10:        0x101fb3b11 - std::panicking::default_hook::hdf696ec8ea0d65aa
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:290:9
    11:        0x101fb43b0 - std::panicking::rust_panic_with_hook::h7c5059af1af54377
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:707:13
    12:        0x1019ee585 - std::panicking::begin_panic::{{closure}}::h5724ac94c880b0e9
    13:        0x101a88979 - std::sys_common::backtrace::__rust_end_short_backtrace::h4d2a42249dd4140f
    14:        0x1019ee515 - std::panicking::begin_panic::h44dd2466cc168f13
    15:        0x1018dc7f9 - build_script_build::build_nss::h4a7bab248dc59cf8
    16:        0x1018de3c4 - build_script_build::setup_standalone::h8685adf5836cc517
    17:        0x1018deb01 - build_script_build::main::h09d2017b94ee2d91
    18:        0x1018c2f5a - core::ops::function::FnOnce::call_once::h508003ee5ae0fd1f
    19:        0x1018c8869 - std::sys_common::backtrace::__rust_begin_short_backtrace::h7e45a12938ff4cbf
    20:        0x1018c17ec - std::rt::lang_start::{{closure}}::hd111de18b56c5f6d
    21:        0x101faa2ba - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hcfff0e1d84ed81c5
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:284:13
    22:        0x101faa2ba - std::panicking::try::do_call::hbabf83ee9c686a7b
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40
    23:        0x101faa2ba - std::panicking::try::he3e9a1c93c50f591
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19
    24:        0x101faa2ba - std::panic::catch_unwind::ha18733e497b82774
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14
    25:        0x101faa2ba - std::rt::lang_start_internal::{{closure}}::hfb6977160fe64fc0
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/rt.rs:148:48
    26:        0x101faa2ba - std::panicking::try::do_call::h385fcb260f1f324b
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40
    27:        0x101faa2ba - std::panicking::try::h3734e87bdbb1b067
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19
    28:        0x101faa2ba - std::panic::catch_unwind::hc13dbc187cd64fe1
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14
    29:        0x101faa2ba - std::rt::lang_start_internal::h54faea1e36783632
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/rt.rs:148:20
    30:        0x1018c17c8 - std::rt::lang_start::h2467b57e93cbe363
    31:        0x1018def78 - _main

```

i don't know why it's not picking up gyp. i installed gyp via git cloning the repository and doing a pip install . and it was successful.

i am sorry for asking this team directly--i know you're not tech support. but this is supposed to be simple and i am frustrated. 

i just want an old version of neqo-crypto. that's all. 

thanks in advance.

**Comment by i3roly** [comment]
fixed it.

GYP needs to be set as an environment variable or on the path.

some may read this and silently say "HUHUHUH (meathead laugh) DUHH" but some of us don't use python.

thanks for providing a forum to ask questions.
