### ISSUE TITLE
`BorrowMutError` in `neqo-transport/src/server.rs`

### ISSUE THREAD

**Issue by larseggert** [mozilla/neqo#1975]
[edit] This seems to be the cause of quite a few interop failures.

In https://interop.seemann.io/logs/2024-07-11T01:40/neqo_picoquic/resumption/output.txt
```
server  | thread 'main' panicked at neqo-transport/src/server.rs:685:26:
server  | already borrowed: BorrowMutError
server  | stack backtrace:
server  |    0: rust_begin_unwind
server  |    1: core::panicking::panic_fmt
server  |    2: core::cell::panic_already_borrowed
server  |    3: neqo_transport::server::ServerConnectionIdGenerator::insert_cid
server  |    4: <neqo_transport::server::ServerConnectionIdGenerator as neqo_transport::cid::ConnectionIdGenerator>::generate_cid
server  |    5: neqo_transport::connection::Connection::output_path
server  |    6: neqo_transport::connection::Connection::process_output
server  |    7: neqo_transport::server::ServerConnectionState::process
server  |    8: neqo_transport::server::Server::process
server  |    9: <neqo_bin::server::http09::HttpServer as neqo_bin::server::HttpServer>::process
server  |   10: neqo_bin::server::ServerRunner::process::{{closure}}
server  |   11: neqo_server::main
```

**Comment by larseggert** [comment]
Same in https://interop.seemann.io/logs/2024-07-11T01:40/neqo_quic-go/handshakeloss/output.txt
```
server  | already borrowed: BorrowMutError
server  | stack backtrace:
server  |    0: rust_begin_unwind
server  |    1: core::panicking::panic_fmt
server  |    2: core::cell::panic_already_borrowed
server  |    3: neqo_transport::server::ServerConnectionIdGenerator::insert_cid
server  |    4: <neqo_transport::server::ServerConnectionIdGenerator as neqo_transport::cid::ConnectionIdGenerator>::generate_cid
server  |    5: neqo_transport::connection::Connection::output_path
server  |    6: neqo_transport::connection::Connection::process_output
server  |    7: neqo_transport::server::ServerConnectionState::process
server  |    8: neqo_transport::server::Server::process
server  |    9: <neqo_bin::server::http09::HttpServer as neqo_bin::server::HttpServer>::process
server  |   10: neqo_bin::server::ServerRunner::process::{{closure}}
server  |   11: neqo_server::main
```

**Comment by larseggert** [comment]
And https://interop.seemann.io/logs/2024-07-11T01:40/neqo_ngtcp2/longrtt/output.txt
```
server  | thread 'main' panicked at neqo-transport/src/server.rs:685:26:
server  | already borrowed: BorrowMutError
server  | stack backtrace:
server  |    0: rust_begin_unwind
server  |    1: core::panicking::panic_fmt
server  |    2: core::cell::panic_already_borrowed
server  |    3: neqo_transport::server::ServerConnectionIdGenerator::insert_cid
server  |    4: <neqo_transport::server::ServerConnectionIdGenerator as neqo_transport::cid::ConnectionIdGenerator>::generate_cid
server  |    5: neqo_transport::connection::Connection::output_path
server  |    6: neqo_transport::connection::Connection::process_output
server  |    7: neqo_transport::server::ServerConnectionState::process
server  |    8: neqo_transport::server::Server::process
server  |    9: <neqo_bin::server::http09::HttpServer as neqo_bin::server::HttpServer>::process
server  |   10: neqo_bin::server::ServerRunner::process::{{closure}}
server  |   11: neqo_server::main
```

**Comment by KershawChang** [comment]
This is also shown on this [try run](https://treeherder.mozilla.org/logviewer?job_id=465886877&repo=try&lineNumber=3672), which means `neqo v0.8.0` is blocked because of this.

@mxinden , could you take a look?
Thanks.

**Comment by mxinden** [comment]
Will investigate further tomorrow. I am under the assumption that no one, other than myself is blocked on this. Correct me if I am wrong. Also, given that this applies to `neqo_transport::server` only, I assume this is not critical for Firefox.

**Comment by larseggert** [comment]
Correct, this isn't blocking and doesn't affect Fx. Prioritize accordingly :-)

**Comment by mxinden** [comment]
> Edit: @KershawChang said it blocks the 0.8.0 vendoring into gecko

Yes. Tracked here: https://phabricator.services.mozilla.com/D216265. Though as far as I know, also not urgent.
