### ISSUE TITLE
WouldBlock, message: "Resource temporarily unavailable"

### ISSUE THREAD

**Issue by larseggert** [mozilla/neqo#2001]
I recently started seeing these test failures. They are not repeatable, but occur occasionally.
```
0s  0ms DEBUG Logging initialized
thread 'tests::datagram_tos' panicked at neqo-udp/src/lib.rs:150:14:
receive to succeed: Os { code: 35, kind: WouldBlock, message: "Resource temporarily unavailable" }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/result.rs:1654:5
   3: core::result::Result<T,E>::expect
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/result.rs:1034:23
   4: neqo_udp::tests::datagram_tos
             at ./src/lib.rs:148:33
   5: neqo_udp::tests::datagram_tos::{{closure}}
             at ./src/lib.rs:134:26
   6: core::ops::function::FnOnce::call_once
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by mxinden** [comment]
Thanks for reporting @larseggert. I expect this to be fixed with https://github.com/mozilla/neqo/pull/2002.
