### ISSUE TITLE
Running examples from README fails

### ISSUE THREAD

**Issue by tomato42** [mozilla/neqo#662]
I compiled neqo on Fedora 30 and both test servers in README don't work. 

 I see that the `neqo-http3-server` is handled in #638 but I don't see a bug for the `neqo-server`

When I execute it as described in README:
```
RUST_BACKTRACE=1 ./target/debug/neqo-server 12345 -k key --db ./test-fixture/db
```
and connect to it with the client:
```
SSLKEYLOGFILE=/tmp/keylog ./target/debug/neqo-client http://127.0.0.1:12345/ -o
```
the server aborts:
```
Server waiting for connection on: V4(0.0.0.0:12345)
New connection from V4(127.0.0.1:42917)
Stream ID 0
Path = 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: Empty }', neqo-server/src/main.rs:112:21
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: core::result::Result<T,E>::unwrap
             at /builddir/build/BUILD/rustc-1.43.1-src/src/libcore/result.rs:1003
  10: neqo_server::http_serve
             at neqo-server/src/main.rs:112
  11: neqo_server::main
             at neqo-server/src/main.rs:191
  12: std::rt::lang_start::{{closure}}
             at /builddir/build/BUILD/rustc-1.43.1-src/src/libstd/rt.rs:67
  13: std::panicking::try::do_call
  14: __rust_maybe_catch_panic
  15: std::rt::lang_start_internal
  16: std::rt::lang_start
             at /builddir/build/BUILD/rustc-1.43.1-src/src/libstd/rt.rs:67
  17: main
  18: __libc_start_main
  19: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by larseggert** [comment]
This seems OBE. Reopen if still an issue, please.
